/*
 * @Author: cold-x
 * @Date: 2025-05-28 15:04:59
 * @LastEditors: cold-x 474647591@qq.com
 * @LastEditTime: 2025-09-15 17:56:02
 * @FilePath: /novel_oversea/lib/global/ui/assets.dart
 * @Description: 
 */
///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  ///tab页
  static const String tabHome = 'assets/global/tab/icon_tab_home.png';
  static const String tabHomeSelected = 'assets/global/tab/icon_tab_home_selected.png';
  static const String tabProfile = 'assets/global/tab/icon_tab_me.png';
  static const String tabProfileSelected = 'assets/global/tab/icon_tab_me_selected.png';
  static const String tabSquare = 'assets/global/tab/icon_tab_tutorial.png';
  static const String tabSquareSelected =
      'assets/global/tab/icon_tab_tutorial_selected.png';
}
