/*
 * @Author: duncy
 * @Date: 2025-09-18 17:57:09
 * @LastEditors: duncy 474647591@qq.com
 * @LastEditTime: 2025-11-04 15:20:38
 * @FilePath: /novel_oversea/lib/firebase_options.dart
 * @Description: 
 */
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdRd2LTO3BXiBlaaRHVlcKu-INmgjYuG8',
    appId: '1:883280627227:android:a8ee637103023c3f07dabe',
    messagingSenderId: '883280627227',
    projectId: 'penman-98b1b',
    storageBucket: 'penman-98b1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUiFRzHhPlDtSaymeC4YJ6IpHL31EDdMg',
    appId: '1:883280627227:ios:f64f9ccc287f6fd007dabe',
    messagingSenderId: '883280627227',
    projectId: 'penman-98b1b',
    storageBucket: 'penman-98b1b.firebasestorage.app',
    iosBundleId: 'com.AI.novel.story.book.generator',
  );

}